import type { api } from '@general-poke/db/api'
import type { FunctionReturnType } from 'convex/server'

import { Link } from '@tanstack/react-router'
import { ArrowLeft, CircleDot, ExternalLink, FileText, Mic } from 'lucide-react'

import {
  useMeetingByIdQuery,
  useTranscriptTurnsQuery,
} from '@/lib/convex/meetings'

type Turn = FunctionReturnType<
  typeof api.public.meeting.queries.listTranscriptTurns
>[number]

const SPEAKER_COLORS: Record<string, string> = {
  A: 'bg-blue-100 text-blue-700',
  B: 'bg-emerald-100 text-emerald-700',
  C: 'bg-amber-100 text-amber-700',
  D: 'bg-purple-100 text-purple-700',
  E: 'bg-pink-100 text-pink-700',
  F: 'bg-indigo-100 text-indigo-700',
}

const STATUS_LABEL: Record<string, string> = {
  created: 'Queued',
  dispatching_listener: 'Bot dispatching…',
  ended: 'Ended',
  failed: 'Failed',
  listener_joining: 'Bot joining…',
  recording: 'Recording',
}

const STATUS_DOT: Record<string, string> = {
  created: 'bg-gray-400',
  dispatching_listener: 'bg-yellow-500 animate-pulse',
  ended: 'bg-gray-500',
  failed: 'bg-red-500',
  listener_joining: 'bg-yellow-500 animate-pulse',
  recording: 'bg-red-500 animate-pulse',
}

type Props = { meetingId: string }

export const MeetingDetail = ({ meetingId }: Props) => {
  const meetingQuery = useMeetingByIdQuery({ meetingId })
  const turnsQuery = useTranscriptTurnsQuery({ meetingId })

  if (meetingQuery.isPending) return <MeetingDetailSkeleton />
  if (!meetingQuery.data) return <MeetingNotFound />

  const meeting = meetingQuery.data
  const turns = turnsQuery.data ?? []
  const live = meeting.status === 'recording'

  return (
    <div className="mx-auto flex w-full max-w-3xl flex-col gap-6 px-6 py-10">
      <div className="flex items-center justify-between">
        <Link
          className="flex items-center gap-1.5 text-sm text-gray-500 hover:text-gray-900"
          to="/"
        >
          <ArrowLeft className="size-4" />
          Back
        </Link>
        {meeting.noteId && (
          <Link
            className="flex items-center gap-1.5 rounded bg-purple-600 px-3 py-1.5 text-sm text-white hover:bg-purple-700"
            params={{ noteId: meeting.noteId }}
            to="/notes/$noteId"
          >
            <FileText className="size-4" />
            View notes
          </Link>
        )}
      </div>

      <div className="flex flex-col gap-3">
        <h1 className="font-serif text-4xl font-medium text-gray-900">
          {meeting.title || 'Untitled meeting'}
        </h1>
        <div className="flex flex-wrap items-center gap-3 text-sm">
          <span
            className={`flex items-center gap-1.5 rounded-md border border-gray-200 px-2.5 py-1 text-xs`}
          >
            <CircleDot
              className={`size-3.5 rounded-full ${STATUS_DOT[meeting.status]}`}
            />
            {STATUS_LABEL[meeting.status]}
          </span>
          <a
            className="flex items-center gap-1.5 rounded-md border border-gray-200 px-2.5 py-1 text-xs text-blue-600 hover:bg-gray-50"
            href={meeting.meetingUrl}
            rel="noreferrer"
            target="_blank"
          >
            <ExternalLink className="size-3.5" />
            Join URL
          </a>
          <span className="text-xs text-gray-500">
            {new Date(meeting._creationTime).toLocaleString()}
          </span>
        </div>
      </div>

      {meeting.status === 'ended' && !meeting.noteId && (
        <div className="rounded border border-purple-200 bg-purple-50 p-3 text-sm text-purple-700">
          Meeting ended. Notes are being generated by the agent — they&apos;ll
          appear here shortly.
        </div>
      )}

      <section className="flex flex-col gap-3">
        <div className="flex items-center gap-2">
          <Mic className="size-4 text-gray-600" />
          <h2 className="font-semibold">
            Live transcript{' '}
            <span className="text-sm font-normal text-gray-500">
              ({turns.length} {turns.length === 1 ? 'turn' : 'turns'})
            </span>
          </h2>
          {live && (
            <span className="flex items-center gap-1 text-xs text-red-600">
              <span className="size-1.5 animate-pulse rounded-full bg-red-500" />
              LIVE
            </span>
          )}
        </div>

        {turns.length === 0 ? (
          <div className="rounded border border-dashed border-gray-200 p-6 text-center text-sm text-gray-500">
            {meeting.status === 'recording'
              ? 'Waiting for first turn…'
              : meeting.status === 'ended'
                ? 'No transcript captured.'
                : 'Transcript will appear here once the bot joins.'}
          </div>
        ) : (
          <ul className="flex flex-col gap-2">
            {turns.map((turn: Turn) => (
              <TranscriptRow key={turn._id} turn={turn} />
            ))}
          </ul>
        )}
      </section>
    </div>
  )
}

const TranscriptRow = ({ turn }: { turn: Turn }) => {
  const label = turn.speakerLabel ?? '?'
  const cls = SPEAKER_COLORS[label] || 'bg-gray-100 text-gray-700'
  return (
    <li className="flex items-start gap-3 rounded border border-gray-200 bg-white p-3">
      <span
        className={`flex size-7 shrink-0 items-center justify-center rounded-full text-xs font-semibold ${cls}`}
      >
        {label}
      </span>
      <p className="flex-1 text-sm leading-relaxed text-gray-800">
        {turn.text}
      </p>
    </li>
  )
}

const MeetingDetailSkeleton = () => (
  <div className="mx-auto flex w-full max-w-3xl flex-col gap-6 px-6 py-10">
    <div className="flex justify-between">
      <div className="h-5 w-16 animate-pulse rounded bg-gray-200" />
      <div className="h-8 w-32 animate-pulse rounded bg-gray-200" />
    </div>
    <div className="h-10 w-2/3 animate-pulse rounded bg-gray-200" />
    <div className="flex gap-2">
      <div className="h-6 w-24 animate-pulse rounded bg-gray-200" />
      <div className="h-6 w-20 animate-pulse rounded bg-gray-200" />
    </div>
    <div className="flex flex-col gap-2">
      <div className="h-14 animate-pulse rounded bg-gray-100" />
      <div className="h-14 animate-pulse rounded bg-gray-100" />
      <div className="h-14 animate-pulse rounded bg-gray-100" />
    </div>
  </div>
)

const MeetingNotFound = () => (
  <div className="mx-auto flex w-full max-w-3xl flex-col items-center gap-3 px-6 py-20 text-center">
    <h1 className="text-2xl font-medium">Meeting not found</h1>
    <Link className="text-sm text-blue-600 hover:underline" to="/">
      Back to home
    </Link>
  </div>
)
